### PR TITLE
Add support for Symfony Mailer

### PR DESCRIPTION
**Pull request by ghost**
Hi @ThomasLandauer , I've been looking at your PR #9 , and I've some changes that I want to suggest to you.

First, I used an optional parameter in the `seeEmailIsSent` function because it is a way to add this new functionality without creating BC, by default it is 'swiftmailer' as before, but if the user so wishes, he can pass 'symfony_mailer' as the second parameter to this function to use that 'Profile Collector'.
```diff
-    public function seeEmailIsSent($expectedCount = null)
+    public function seeEmailIsSent($expectedCount = null, $mailer = 'swiftmailer')
```
Secondly, I validated that at least one of the 'Profile Collector' exists:
```diff
+        switch ($mailer) {
+            case 'swiftmailer':
                if (!$profile->hasCollector('swiftmailer')) {
                    $this->fail(
                         'Emails can\'t be tested without SwiftMailer connector.
+                        If you are using Symfony Mailer use "symfony_mailer" as second parameter'
                    );
                }
+                break;
+            case 'symfony_mailer':
+                if (!$profile->hasCollector('mailer')) {
+                    $this->fail('Emails can\'t be tested without Symfony Mailer connector');
+                }
+                break;
+            default:
+                $this->fail('Invalid mailer argument. Allowed Options: "swiftmailer" or "symfony_mailer"');
+        }
```
Then, I added this logic, in this case it's enough to write 'else' and not 'elseif' since above we verified that there is a valid 'Profile Collector'.
```diff
+        if ($mailer === 'swiftmailer') {
            $realCount = $profile->getCollector('swiftmailer')->getMessageCount();
+        } else {
-           $realCount += count($profile->getCollector('mailer')->getEvents()->getMessages());
+           $realCount = count($profile->getCollector('mailer')->getEvents()->getMessages());
+        }
```
And finally I took the opportunity to add support for Symfony Mailer in the `debugResponse` function, in this way the complete module is now compatible with Symfony Mailer without breaking the code of the users who use it with Swift Mailer. (So ​​the name of the PR should change).
```diff
            if ($profile->hasCollector('swiftmailer')) {
                $messages = $profile->getCollector('swiftmailer')->getMessageCount();
                if ($messages) {
                    $this->debugSection('Emails', $messages . ' sent');
                }
+            } elseif ($profile->hasCollector('mailer')) {
+                $messages = count($profile->getCollector('mailer')->getEvents()->getMessages());
+                if ($messages) {
+                    $this->debugSection('Emails', $messages . ' sent');
+                }
             }
```
I'll stay tuned to your comments. Cheers!

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
Yeah, I have to admit that I didn't take care about SwiftMailer ;-) So this is certainly a good idea!

The problem I'm seeing is this: If we now introduce `$I->seeEmailIsSent(1, 'symfony_mailer');` how can we *ever* get rid of the second argument again? We'd need to change the default value, which is a BC break, and will take, well, forever...

So I have another idea: Put it into the config file `functional.suite.yml`! Something like:
```yaml
modules:
    enabled:
        - Symfony:
            mailer: 'swiftmailer' # or 'symfony_mailer'
```
Advantages:
* Set it once, then forget about it
* I doubt that anybody uses both mailers in parallel. But even this would be possible, since you can change the configuration on the fly with `$this->getModule('Symfony')->_reconfigure(['mailer' => 'swiftmailer']);`

What do you think?

**Comment by ghost** [comment]
Even better 👍 
now I just have to see how I write that 🤣 , but it looks interesting
i will try to do it that way, thanks you

**Comment by ghost** [comment]
Ok, i think i got it. 😃 
```yaml
modules:
    enabled:
        - Symfony:
            mailer: 'symfony_mailer'
```
and
```php
        //...
        $I->seeEmailIsSent(2);
```
results in:
```
Time: 00:12.905, Memory: 24.00 MB

OK (1 tests, 1 assertions)
```

**Comment by ThomasLandauer** [comment]
I'm merging this, but I didn't double-check it :-)

**Comment by ThomasLandauer** [comment]
@TavoNiievez looks like there are some problems - could you take a look? https://github.com/Codeception/module-symfony/actions/runs/205934965

**Comment by ghost** [comment]
@ThomasLandauer I saw them a couple of weeks ago when you merged, but it seems to be a dependency related issue installing the project (friendsofphp/php-cs-fixer 3 with symfony/console 5 to be exact) and not really with the code I edited. Resolving those conflicts should be a separate PR.

**Comment by ThomasLandauer** [comment]
OK, I wasn't sure if you'd get the notification too.

BTW: I think the main problem is that the Symfony module currently doesn't have a maintainer. Would you be interested?

**Comment by ghost** [comment]
For me it would be a pleasure to help.

I just joined as a [Specify](https://github.com/Codeception/Specify) and [Verify](https://github.com/Codeception/Verify) maintainer and I would like to implement some changes in [Module Asserts](https://github.com/Codeception/module-asserts) and [Lib Asserts](https://github.com/Codeception/lib-asserts),

but **_after_** that I was planning to send PR's to the Symfony Module and the [Doctrine Module](https://github.com/Codeception/module-doctrine2).

It's just that I think it's essential to do the work first in those libraries that are smaller and then make changes in a slightly more complex one like the Symfony module.

so my answer is: 'Eventually yes' 😃

**Comment by ThomasLandauer** [comment]
@DavertMik, @Naktibalda are you still looking for a maintainer of the Symfony module? https://github.com/Codeception/Codeception/issues/4243#issuecomment-303548165 May I suggest TavoNiievez?

**Pull request merged**
